<div class="block small center login">
	<div class="block_head">
		<div class="bheadl">
		</div>
		<div class="bheadr">
		</div>

		<h2>Daemon Watch - Reset Password</h2>
	</div>

	<div class="block_content">
		<p>Enter your email address to reset your password</p>
		<?= $this->render('misc/show_errors.phtml'); ?>
				
		<form method="post" id="resetPasswordForm">
			<p>
				<label for="userEmail">
					Email *
				</label><br>
			
				<input type="text" name="email" autocomplete="off" class="required email text" placeholder="registered email"> 
			</p>
			<br>	
			
			<p>
				<input type="submit" value="Reset" class="submit">
			
				<a href="<?= $this->baseUrl(); ?>/auth/login">Back</a>
			</p>
		
		</form>

	</div>

	<div class="bendl">
	</div>
	<div class="bendr">
	</div>
</div>
