<div class="block small center login">

	<div class="block_head">
		<div class="bheadl">
		</div>
		<div class="bheadr">
		</div>

		<h2>Add Host</h2>
	</div>

	<div class="block_content">
		<?= $this->render('misc/show_errors.phtml'); ?>
		
		<form method="post" id="addHostForm">
			<p>
				<label for="name">
					Name *
				</label>
				<br>
				<input type="text" name="name" autocomplete="off" value="<?= $this->formData['name']; ?>" class="text required" placeholder="name of host"> 
		
			</p>
		
			<p>
				<label for="hostName">
					Hostname or IP *
				</label>
				<br>		
				<input type="text" name="hostName" autocomplete="off" value="<?= $this->formData['hostName']; ?>" class="required text" placeholder="hostname or IP address of host">
			</p>
				
			
			<div align="center">
				<input type="submit" value="Add Host" class="submit">
			</div>
		
			<br />
			
		</form>

	</div>

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>			