<div class="block small center login">

	<div class="block_head">
		<div class="bheadl">
		</div>
		<div class="bheadr">
		</div>

		<h2>Change Password</h2>
	</div>

	<div class="block_content">
		<?= $this->render('misc/show_errors.phtml'); ?>
		
		<form method="post" id="changePasswordForm">
			<p>
				<label for="newPassword">
					New Password *
				</label><br>
			
				<input type="password" name="newPassword" autocomplete="off" class="text required"> 
			</p>
		
			<p>
			<label for="password">
				Repeat Password *
			</label><br>
		
			<input type="password" name="repeatPassword" autocomplete="off" class="text required">
			</p>
							
			<div align="center">
				<input type="submit" value="Update Password" class="submit long required email">
			</div>
		
		</form>

	</div>

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>	