<div class="block">

	<div class="block_head">
		<div class="bheadl">
		</div>
		<div class="bheadr">
		</div>

		<h2>Home</h2>

	</div>

	<div class="block_content">
		<?php if (!empty($this->userSummary)) { ?>
			<table class="list">
				<thead>
					<tr>
						<th>Host #</th>
						<th>Active Services #</th>
						<th>Avg Connect Time</th>
						<th>Service Availability</th>
						<th>Service Downtime</th>
					</tr>
				</thead>
				
				<tbody>
					<tr>
						<th><?= $this->userSummary['hosts']; ?></th>
						<th><?= $this->userSummary['services']; ?></th>
						<th><?= $this->userSummary['avg_latency']; ?> ms</th>
						<th><?= $this->userSummary['up_percent']; ?> %</th>
						<th><?= $this->userSummary['down_percent']; ?> %</th>													
					</tr>
				</tbody>	
			</table>
			
		<?php } else { ?>
			<p>Unable to show summary.</p>
		<?php } ?>
		<br />	
		<script type="text/javascript">
		window.onload = function() {
			$(document).ready(function(){
			  var graphData = [];
			  <?php
					$xData = '';
					$latencyGraphData = '';
					$x = 0;
					foreach ($this->latencyGraphData as $latencyGraphData) {
						$x++;
						if (!empty($latencyGraphData['timeTaken'])) {
							echo 'graphData.push([' . $x . ',' . $latencyGraphData['timeTaken'] . ']);';
						}
					}
			  ?>								
			  var plot1 = $.jqplot('latencyGraphHolder', [graphData], {  
			      series:[{showMarker:false}],
			      title: 'Service Latency Over Time', 
			      axes:{
			        xaxis:{
			          label:'Service checks',
			          labelRenderer: $.jqplot.CanvasAxisLabelRenderer
			        },
			        yaxis:{
			          label:'Latency (Milliseconds)',
			          labelRenderer: $.jqplot.CanvasAxisLabelRenderer
			        }
			      }
			  });
			});	
			
			<?php
				echo  "var plot2 = $.jqplot('uptimeGraphHolder', [[['Downtime Detected',".$this->uptimeGraphData['serviceDown']."],['Services Up',".$this->uptimeGraphData['serviceUp']."]]], {\r\n";
			?>
			      title: 'Host Uptime',
			      seriesColors: [ "#f30909", "#1fe028"],
			      seriesDefaults: {
			        renderer: jQuery.jqplot.PieRenderer,
			        rendererOptions: {
			          showDataLabels: true
			        }
			      },
			        legend:{
			            show:true
			        } 
		    });			
		};		
		</script>
		
		<div id="latencyGraphHolder"></div>
		
		<div class="clear"></div>
		
		<br />
		
		<div id="uptimeGraphHolder" style="width:500px; height:400px;"></div>
	</div>		

	<div class="bendl"></div>
	<div class="bendr"></div>
	
</div>	