<div class="block">

	<div class="block_head">
		<div class="bheadl">
		</div>
		<div class="bheadr">
		</div>

		<h2>Traceroute</h2>

	</div>

	<div class="block_content">
			<div id="errorMsg">
				<?php
					if (!empty($this->tracerouteError)) {
						foreach($this->tracerouteError as $tracerouteError) {
							echo $tracerouteError . "<br>";			
						}
					}	
				?>	
			</div>
			
			<form method="post" id="performTraceroute">
				<label for="host">
					Host:
				</label>
				
				<input type="text" name="hostname" class="required" placeholder="Host / IP to trace">
				
				
				<input type="submit" value="Traceroute">
			</form>
			
			<br />
			
			<?php
				if (!empty($this->tracerouteResult)) {
					foreach($this->tracerouteResult as $traceroute) {
						echo $traceroute . "<br />";
					}		
				}	
			?>
	</div>
	

	<div class="bendl"></div>
	<div class="bendr"></div>
	
</div>	