<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=7" />
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle($this->title); ?>
	    <style type="text/css" media="all">
			@import url("<?= $this->baseUrl(); ?>/css/style.css");
	    </style>        
        <script src="<?= $this->baseUrl(); ?>/js/jquery.js" type="text/javascript"></script>
        <?php echo $this->headScript(); ?>
		<?php
		if(!empty($this->js)) {
			if (count($this->js) > 0) {
				foreach($this->js as $js) {
					echo '<script src="'.$this->baseUrl().'/js/'.$js.'" type="text/javascript"></script>' . "\r\n";
				}
			}
		}
		?>   
    </head>
    <body>
		<div id="hld">	
			<div class="wrapper">						
 				   	<?= $this->layout()->content;?>					
			</div>
		</div> 				   	
    </body>
    </html>