<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=7" />
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle($this->title); ?>
	    <style type="text/css" media="all">
			@import url("<?= $this->baseUrl(); ?>/css/style.css");
			@import url("<?= $this->baseUrl(); ?>/css/facebox.css");			
	    </style>        
        <script src="<?= $this->baseUrl(); ?>/js/jquery.js" type="text/javascript"></script>
        <?php echo $this->headScript(); ?>
		<?php
		if(!empty($this->js)) {
			if (count($this->js) > 0) {
				foreach($this->js as $js) {
					echo '<script src="'.$this->baseUrl().'/js/'.$js.'" type="text/javascript"></script>' . "\r\n";
				}
			}
			echo '<!--[if lt IE 9]><script language="javascript" type="text/javascript" src="'.$this->baseUrl().'/js/excanvas.min.js"></script><![endif]-->' . "\r\n";
		}
		?>  
		
		<script type="text/javascript">
			// Navigation dropdown fix for IE6
			if(jQuery.browser.version.substr(0,1) < 7) {
				$('#header #nav li').hover(
					function() { $(this).addClass('iehover'); },
					function() { $(this).removeClass('iehover'); }
				);
			}	
		</script>		 
    </head>
    <body>
		<div id="hld">
			<div class="wrapper">
				<?= $this->render('misc/header.phtml') ?>
				<?= $this->layout()->content;?>
			</div>
		</div>
    </body>
    </html>